services:
  limboole-diff:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: limboole-diff
    ports:
      - "8080:8080"
    environment:
      API_URL: http://localhost:8000